### GET endpoint for '/'
GET http://localhost:5000

### POST endpoint '/api/jobs' to create a valid job 
POST http://localhost:5000/api/jobs
Content-Type: application/json

{
    "title": "Fix bulb in kitchen",
    "description": "The kitchen bulb has been dimed for a week",
    "category": "Electrical",
    "location": "Glasgow",
    "contactName": "Kenul Smith",
    "contactEmail": "Kenul@example.com"
}


### GET edpoint for list of all jobs with optional filters
GET http://localhost:5000/api/jobs


### GET endpoint fot specific job request
GET http://localhost:5000/api/jobs/6a0863744faac5a340711c0a

### PATCH endpoint to update the request's status

PATCH http://localhost:5000/api/jobs/6a0863744faac5a340711c0a
Content-Type: application/json

{
    "status": "In Progress"
}

### DELETE endpoint for deletion of specific user
DELETE http://localhost:5000/api/jobs/6a0825fd62a8b4160f89073f


### ERROR handling : Missing required fields (ValidationError)
POST http://localhost:5000/api/jobs
Content-Type: application/json

{
    "category": "Plumbing"
}

### ERROR handling : Invalid ID format (CastError)
GET http://localhost:5000/api/jobs/abc123


### ERROR handling : Test 3 — Invalid status value

PATCH http://localhost:5000/api/jobs/6a08257162a8b4160f89073d
Content-Type: application/json

{
    "status": "Completed"
}